### ISSUE TITLE
disable/enable overlay 

### ISSUE THREAD

**Issue by ranshalit** [gfleury/overlayroot#2]
Hello,

Is it possible to change to non-overlay ?

Thanks,
ran

**Comment by gfleury** [comment]
Hello @ranshalit , 

I'm not sure if I understood your question. You mean to revert after using overlay?

George Fleury

**Comment by ranshalit** [comment]
yes, I mean enable/disable the overlay.
Thanks!

**Comment by gfleury** [comment]
Yes, 
You could just remove the line from /etc/overlayroot.conf and rerun dracut. 
```
# echo "" > /etc/overlayroot.conf
# dracut -f /boot/initramfs-4.9.20-10.30.amzn1.x86_64.img 4.9.20-10.30.amzn1.x86_64
```
(keep in mind that I have not tested this, but, from what I remember this should work)

**Comment by ranshalit** [comment]
Hi gfleury,

Thanks, if I may I would like to ask another thing (please tell me if you prefer to put it on a separate issue).
1. I need to use it with centos, and since I see that it use dracut I assume that this is perfect for centOS, becuase centOS does not support initramfs-tools, Right ?
2. Another thing is that I see that it use Amazon EBS , but I think will use ext4 instead. Is it possible to use it with ext4 ?

Thank for the time,

**Comment by gfleury** [comment]
Hi, 

No problem, we can discuss on this thread. 
1) Yes, it was tested on Amazon Linux which is a port from RHEL 'similar' to CentOS. It should work perfectly. 
2) Amazon EBS is the block device. OverlayFS works with different filesystems, including xfs and ext4. Direct answer, yes you can use ext4. 

Thanks, 

George Fleury

**Comment by ranshalit** [comment]
Hello Gregory,

Thank you for the answers. 
I would please like to ask if the device can be jut any partition , instead of full device as shown in your git overlay.conf example : 
 #overlayrootdevice=/dev/nvme0n1
(for example,  nvme0n1p1 instead of nvme0n1)

Thanks,
ranran

**Comment by ranshalit** [comment]
Just to be more clear, I mean that I have several partitions in fstab, some of them need to be writable even with the overlay rootfs, is that possible or is it assume that all partitions in fstab should be  overlayed ?

**Comment by gfleury** [comment]
> Hello Gregory,
> 
> Thank you for the answers.
> I would please like to ask if the device can be jut any partition , instead of full device as shown in your git overlay.conf example :
> #overlayrootdevice=/dev/nvme0n1
> (for example, nvme0n1p1 instead of nvme0n1)
> 
> Thanks,
> ranran

Yes. You can.

**Comment by gfleury** [comment]
> Just to be more clear, I mean that I have several partitions in fstab, some of them need to be writable even with the overlay rootfs, is that possible or is it assume that all partitions in fstab should be overlayed ?

Can you provide more details? I'm not sure if I understood the question.

**Comment by ranshalit** [comment]
Hello Gregory,

I mean that I have several partitions in the device:
1. mmcblk0p1 - boot partition
2. mmcblk0p2 - root filesystem partition <<-- I want only to this partition to be overlayed
3. mmcblk0p3 - user (home) partition

But it seems that this script overlay all partitions in device mmcblk0, Right ?
( overlay.conf use device, not partitions)

Thanks

**Comment by gfleury** [comment]
Thanks for clarifying Ranran, 

So, overlay.conf can use devices or partitions. In your case you will use mmcblk0p2. 
Then the other partitions will remain working as normal.

**Comment by ranshalit** [comment]
Thank you very much for the kind answers !

I'll start trying this project on my device right now...

By the way, my rootfs partition is xfs, so I changed :
in overlay\install
```
....
dracut_install  mkfs.xfs
```
and in mount-overlayroot.sh:
```
...
mount $overlayrootdevice /run/root-rw || ((mkfs.xfs -F $overlayrootdevice && mount 

```
Thanks again!

**Comment by gfleury** [comment]
Sureeee man! Yeah, we may parametrize this to make it better, choosing the filesytem type. We are open to PR's! =)
