### ISSUE TITLE
Issues with centOS

### ISSUE THREAD

**Issue by ranshalit** [gfleury/overlayroot#3]
Hi,

I tried to install it on centOS 7.
I made:
```
make 
make install
```
(didn't make the rpm)

and than do the following:
```
dracut -f
```
in /etc/overlayroot.conf I see my rootfs partition:
```
overlayrootdevice=/dev/mmcblk1p2
```
I see that new initramfs was created for my kernel, but on testing it, I see that files are non-volatile (as if no overlay at all).

This is what I tried:
1. I rechecked that kernel (4.14.87) support overlay (overlay_fs=y).
2. I then tried to figure out if initramfs shows any error or printing , but I am not sure how to do that , is there a way to see if initramfs runs ?
 
I see that even if I delete the line from grub with `initrd16 /initramfs-4.14.87-rt49.img` linux boot correctly (which is quite surprising...) ! 

Thanks for the help!

**Comment by gfleury** [comment]
Try installing the rpm, (it will not use xfs on the top fs as you expect, but just for testing purposes)

rpm -ivh https://s3.amazonaws.com/gfleury/dracut-modules-overlayroot-0.1-beta.amzn1.noarch.rpm

I never tested with CentOS. I could give a try later.

**Comment by gfleury** [comment]
Try this RPM, 

https://github.com/gfleury/overlayroot/releases/download/v0.1/dracut-modules-overlayroot-0.1-beta.el7.noarch.rpm


The 'make install' is only intended to use from inside rpmbuild. That's why it doesn't work.

**Comment by gfleury** [comment]
Actually, I tried to use and found a few issues with CentOS 7.
I will see if I can provide a proper solution.

**Comment by ranshalit** [comment]
Thank you very much for your help. It's really appreciated !!!!

I also found some stuff if that helps:
1. I had to copy to /usr/lib/dracut (instead of just /dracut) because "dracut -f" use that
2. I had to rename and modify install to module-setup.sh

Next I also enabled log of initramfs as part of kernel parameters :
`rd.shell rd.debug log_buf_len=1M `

I than saw that mount-overlay.sh is trying to use mkfs.xfs and fails because there is no "-F" parameter, so I removed that parameter.
Yet, it still fail in mount as you can see here (search fail word)
https://pastebin.com/SSP5SxiE

I am continuing on trying to debug it.

Thank you very much for your assistance!

**Comment by ranshalit** [comment]
I have also noticed the following (from my above previous message ):
```
: mount: /dev/mmcblk1p2 is already mounted or /run/root-rw busy
: /dev/mmcblk1p2 is already mounted on /sysroot
```

I think it gives indication for the problem, but I don't yet understand what it is.

**Maybe the 50overlayroot should actually start before some other module in the centos dracut which already mounted this partition ?**

I also tried to umount /sysroot (just before starting the mount), but now it enters emergency mode....

Thanks

**Comment by gfleury** [comment]
@ranshalit try uninstall the other rpm, and install this one, 
https://github.com/gfleury/overlayroot/releases/download/v0.1/dracut-modules-overlayroot-0.2-beta.el7.noarch.rpm

and follow the same procedures. I have it working on a CentOS7 here. 
```
/dev/sda1 on /run/sysroot type ext4 (ro,relatime,seclabel,data=ordered)
/dev/sdb on /run/root-rw type ext4 (rw,relatime,seclabel,data=ordered)
overlay on / type overlay (rw,relatime,seclabel,lowerdir=/run/sysroot,upperdir=/run/root-rw/root,workdir=/run/root-rw/workdir)
```

**Comment by ranshalit** [comment]
Thank you,
I understand it is working only with ext4, Right ? 
Can you please share a zip file of the sources too ?

Thank you

**Comment by ranshalit** [comment]
Thank you, I will try it now.

**Comment by ranshalit** [comment]
Sorry for being nudge, It still doesn;t work on my side, with this rpm.

This is what I do step by step:
1.  I installed fresh centos 7 on my virtual machine:
/dev/sda1 - boot
/dev/sda2 - rootfs
(no swap partition)
I format all partitions with ext4  !

2. I've installed the rpm (rpm -ivh ...) + verified all files are installed in correct folders (/usr/lib/dracut /etc etc, and they are installed correctly with rpm (no change)

3.  /etc/overlayrootconf.sh contents is:
overlayrootdevice=/dev/sda2 
(I also tried /dev/sda - no change)

4. Then do: dracut -f

5. after reset, in home folder do: touch xxx , reset device, and being surprsied to still find the "xxx" file after reset :( 

What am I doing wrong ?

Thank you so much

**Comment by ranshalit** [comment]
Just to add to my previous message above, this is the log from dracut:

> [    2.268223] dracut-pre-pivot[1397]: ///lib/dracut/hooks/pre-pivot/10-mount-overlayroot.sh@139(source): mount /dev/sda2 /run/root-rw
> [    2.275339] dracut-pre-pivot[1397]: mount: /dev/sda2 is already mounted or /run/root-rw busy
> [    2.275605] dracut-pre-pivot[1397]: /dev/sda2 is already mounted on /sysroot
> [    2.276153] dracut-pre-pivot[1397]: ///lib/dracut/hooks/pre-pivot/10-mount-overlayroot.sh@139(source): mkfs.ext4 -F /dev/sda2
> [    2.277100] dracut-pre-pivot[1397]: mke2fs 1.42.9 (28-Dec-2013)
> [    2.277314] dracut-pre-pivot[1397]: /dev/sda2 is mounted; will not make a filesystem here!
> [    2.277762] dracut-pre-pivot[1397]: ///lib/dracut/hooks/pre-pivot/10-mount-overlayroot.sh@139(source): echo Fail mount /dev/sda2. Falling back to root device.
> [    2.278166] dracut-pre-pivot[1397]: ///lib/dracut/hooks/pre-pivot/10-mount-overlayroot.sh@139(source): return 1

**Comment by gfleury** [comment]
So, the problem is that you added the root partition on the overlayroot.conf. On the file overlay.conf you should point the FILESYSTEM THAT WILL BE USED AS OVERLAY ON TOP of the rootfs, not the rootfs itself. 

example, 
/dev/sda1 - boot
/dev/sda2 - rootfs

/dev/sdb1 - New partition that you want to use as overlay.

then, you add on overlayroot.conf
overlayrootdevice=/dev/sdb1


This will mount /dev/sdb1 on top of /dev/sda2, and all modifications will be written to sdb1 while sda2 will keep intact.

**Comment by gfleury** [comment]
About the XFS and disabling it, I will try to add an option to that.

**Comment by gfleury** [comment]
But is everything under the PR #4

**Comment by ranshalit** [comment]
Thank you 
That's right ! This is what I missed in my understanding of the conf file !

I fixed that.
The only thing left is that now after enterning password it starts with:
"Welcome to emregency mode"
**Did you also noticed this mode after reboot into the overlayed kernel or is it only in my system ?**

Maybe I need to make the rootfs the first partition ?
I noticed that it is the 1st partition in your above example ? So should I swap
/dev/sda1 - boot
/dev/sda2 - rootfs
and use instead to:
/dev/sda1 - rootfs
/dev/sda2 - boot

Thanks

**Comment by gfleury** [comment]
No, the example I just wrote from the top of my head. Try to do it from the scratch again. It should work out of the box. 
Running it multiple times with different configurations probably will generate a broken /etc/fstab file.

**Comment by ranshalit** [comment]
see the boot screen after my reboot:
https://pasteboard.co/IsYW1jz.jpg

It still login after enterning password.
I wander if you also got the same thing with centos.

Thanks

**Comment by gfleury** [comment]
Hmm, no, my CentOS 7 boot normally. Can you provide more details on how are you 'installing' this centos? maybe I can reproduce it here.

**Comment by ranshalit** [comment]
Hi,

**Thank you very much for the help, it's highly appreciated!**

This is what I do step by step:

1. I installed fresh centos 7 (Official release in site, CentOS-7-x86_64-DVD-1810)  on my virtual machine. I use 2 storage device: sda (for boot and rootfs) + sdb (for overlayfs)
32GB for sda and 2GB for sdb

In centos install, I changed the partition layout from LVM to standard, and changed all partition from xfs to ext4, also removed swap partition:

/dev/sda1 - boot
/dev/sda2 - rootfs
(I also deleted the swap partition)


2. I've installed the rpm you have put in here: 
rpm -ivh dracut-modules-overlayroot-0.2-beta.el7.noarch  

3.  I've edited
/etc/overlayrootconf.sh contents is:
overlayrootdevice=/dev/sdb
(I also tried /dev/sda - no change)

4. Since the 3.10 kernel which comes with centos7 has FS_OVERLAY=M, while we need it as boot (FS_OVERLAY=Y), therefor I downloaded another kernel 4.14.52 changed the config from FS_OVERLAY=m to FS_OVERLAY=Y, made "make" , "make install", (if I will not do this the initramfs complain that there is no overlayfs),


5. from 3.10 kernel boot I do:
Then do: dracut -f /boot/initramfs-4.14.52.img 4.14.52

6. I boot  into 4.14.52 kernel (choosing 4.14.52 in grub)
   It seems that there are no errors in initramfs, yet it boot into emergency mode (by the way, if I boot again into 3.10,  delete content of /etc/overlayrootconf.sh , recreate initramfs, and boot again into 4.14.52, than I start 4.14.52 kernel regular login without issues)

**I suspect that maybe it's required that the first partition must be rootfs ( and the second for the boot partition) , because in my above steps 2nd partition is used for rootfs, while in your message above sda1 partition (1st partition)  is used for rootfs ? Could this be the problem ?**

I don't know what I am missing here.... 
If I could see a desktop record of how you did it all it could help. I really eager to understand what's wrong in my steps.

**Thank you very much for everything.**

**Comment by gfleury** [comment]
So, you would not need to recompile the kernel. OVERLAY as module is ok, this is how I'm using. 
Second fact is that you again mentioned  overlayrootdevice=/dev/sda2. 
This will not work, sda2 is the original rootfs, you need another disk or partition like sdb or sdb1.

**Comment by gfleury** [comment]
As I can see, could be this new kernel you are using and also the wrong configuration of overlayroot.conf.

**Comment by ranshalit** [comment]
Sorry ! the sda2 was typo in my above message, (I actually used /dev/sdb after you said ) I've edit the above message. sorry for this.

When I used same original kernel (with FS_OVERLAY=m) I got error in initramfs (yet, I will try now again)
Do you mean you use insmod to overlay module ?

What is your partition layout ? is it
/dev/sda1 - rootfs
/dev/sda2 - boot 
?
**Maybe the whole issue is that we must use 1st partition for rootfs ?** (as I wrote I use 1st partition as boot, so I suspect the script requires 1st boot to be rootfs. what do you think ?)

Thanks

**Comment by ranshalit** [comment]
I tried again with fresh install, and without doing any change in kernel, it also seems to fail.
I also see that overlay is not supported after boot , by doing "cat /proc/filesystem"
And this make sense.
If no script is doing "insmod overlay", than overlay is not supported.
What am I doing wrong :(((

**Comment by ranshalit** [comment]
If I could know the precise steps you've done, I can try doing the same on my machine.
I assume that the steps you're doing are not totally default choices when installing centos, becuase you have rootfs in 1st partition for example.

I am also not sure about kernel update ? Do I need to install another kernel ? I have tried to download kernel-4.9.20-10.30.amzn1.x86_64, but haven't find it .... 
Is it that the kernel you are using: is it the default 3.10 kernels that comes with centOS 7 ?  I ask because when I try to use that kernel overlay fs is not supported in the initramfs yet ( maybe there is "insmod overlay"  somewhere in dracut modified module scripts which are not available in rpm ?)

Thank you very much

**Comment by ranshalit** [comment]
I've tried to repeat centos install and overlay rpm install, (using /dev/sdb for overlay device), but I get the same "welcome to emergency mode" result.

**Comment by ranshalit** [comment]
Hi,

I hope you're not too much tired of me :) 

I've put in youtube a video record of my exact steps:
https://youtu.be/dV5B9p4mkpg


Thanks

**Comment by gfleury** [comment]
Hello, 

Ok, among other problems seems that dracut version of CentOS is not respecting the parameters from his modules to install dependent kernel modules.

Try a fresh install with this RPM, (I updated it, it works only with XFS btw)

https://github.com/gfleury/overlayroot/releases/download/v0.1/dracut-modules-overlayroot-0.2-beta.el7.noarch.rpm


```
/dev/mapper/centos-root on /run/sysroot type xfs (ro,relatime,seclabel,attr2,inode64,noquota)
/dev/sdb on /run/root-rw type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
overlay on / type overlay (rw,relatime,seclabel,lowerdir=/run/sysroot,upperdir=/run/root-rw/root,workdir=/run/root-rw/workdir)
```

and try something, 
add "-vvvvvv"  parameter to dracut. 
like dracut -vvvvv -f /boot....
it will print a list of all included files into the ramfs, check if overlay.ko is there. 

if not, what worked was running something like this

modprobe overlay && dracut -vvvv -f /boot/initramfs-3.10.0-957.27.2.el7.x86_64.img  3.10.0-957.27.2.el7.x86_64 


Follow all my history on the VM I tested. 

```
    1  pwd
    2  ls
    3  yum update -y
    4  reboot
    5  rpm -ivh https://github.com/gfleury/overlayroot/releases/download/v0.1/dracut-modules-overlayroot-0.2-beta.el7.noarch.rpm
    6  vi /etc/overlayroot.conf 
    7  ps auxww
    8  dmesg |grep sdb
    9  mkfs.xfs -f /dev/sdb
   10  pwd
   11  ls
   12  s -la
   13  ls -la
   14  uname -a
   15  dracut -vvvvv -f /boot/initramfs-3.10.0-957.27.2.el7.x86_64.img  3.10.0-957.27.2.el7.x86_64 
   16  modprove overlay
   17  modprobe overlay
   18  dracut -vvvvv -f /boot/initramfs-3.10.0-957.27.2.el7.x86_64.img  3.10.0-957.27.2.el7.x86_64 
   19  reboot
   20  mount
   21  history
```

**Comment by ranshalit** [comment]
Great work, man ! It works :))))
I really appreciate your assistance thought this issue.

**Comment by ranshalit** [comment]
The issue was the default fstab, it contained the following line: 
`/dev/mapper/centos-home /home ....`
after removing this line there were no errors
I have understood that from the following error during boot :
`overlayfs: failed to resolve /run/root-rw/root/home `

Thank you again for this project !

**Comment by gfleury** [comment]
Yeah, this is an issue if you have other partitions.. I will make it check only for the rootfs.
